# This is a basic workflow to help you get started with Actions

name: AzureWebApps

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
    
      # Build package using Maven
      - name: maven build, clean
        run: |
          mvn clean package -D skipTests
    
      # Maven plugin can cosume this authentication method automatically
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Select your way to deploy below
      # (Maven / webapp-deploy with ServicePrincipal / webapp-deploy with PublishProfile)
    
      # Maven deploy, make sure you have correct configurations in your pom.xml
      - name: deploy to Azure App Service using Maven
        run: |
          mvn azure-webapp:deploy
